pool:
  vmImage: 'ubuntu-latest'

name: $(BuildID)-$(Build.SourceBranchName)

stages:
- stage: build
  jobs:
  - job: buildFront
    steps:
    - task: Npm@1
      displayName: npm ci
      inputs:
        command: 'ci'
    - task: Npm@1
      displayName: build to deploy folder
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - publish: deploy
      artifact: front-pack
  
- stage: dockerImage
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: dockerBuild
    steps:
    - download: current
      artifact: front-pack
      displayName: Download front-pack
    - task: Docker@2
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/sber-realityshift-front'
        command: 'buildAndPush'
        Dockerfile: '$(Pipeline.Workspace)/front-pack/Dockerfile'
        buildContext: '$(Pipeline.Workspace)/front-pack'
        tags: |
          $(Build.BuildId)
          latest

- stage: deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - deployment: DeployFront
      displayName: Deploy front
      pool:
        vmImage: 'Ubuntu-16.04'
      environment: 'production'
      strategy:
        runOnce:
          on:
            failure:
              steps:
                - download: none
                - task: SSH@0
                  inputs:
                    sshEndpoint: 'swarm manager'
                    runOptions: 'commands'
                    commands: 'docker service rollback sber-realityshift_front'
                    readyTimeout: '20000'
          deploy:
            steps:
              - download: none
              - task: SSH@0
                inputs:
                  sshEndpoint: 'swarm manager'
                  runOptions: 'commands'
                  commands: 'docker service update --image rtuitlab/sber-realityshift-front:$(Build.BuildId) sber-realityshift_front'
                  readyTimeout: '20000'